name: CI
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # windows-latest still not supported by tree-sitter/setup-action@v1

    steps:
      - name: Clone tree-sitter-systemverilog
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses:  tree-sitter/setup-action/cli@v1

      # need json lock file
      - name: Install dependencies
        #run: npm ci --omit dev --omit peer --omit optional
        run: npm ci --omit dev
      - name: version check
        run: tree-sitter -V

      - name: Generate parser
        run: |
          tree-sitter generate

      # - name: Run tests
      #   run: |
      #     tree-sitter test
          
      # - name: Test python binding
      #   uses: tree-sitter/parser-test-action@v2
      #   with:
      #     test-python: true
      #     test-parser: false

      # - name: Test other binding
      #   uses: tree-sitter/parser-test-action@v2
      #   with:
      #     test-rust: true
      #     test-go: true
      #     test-swift: false
      #     test-parser: false
          
      # - name: Test node binding
      #   uses: tree-sitter/parser-test-action@v2
      #   with:
      #     test-node: true
      #     test-parser: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest
          cache-dependency-path: package-lock.json
      - name: Build module
        shell: sh
        run: npm install
      - name: install tree-sitter
        shell: sh
        #run: npm install tree-sitter@0.22.4
        run: npm install --force -no-optional tree-sitter@github:MaximusSeniorem/node-tree-sitter#up_core_lib
      - name: list module
        shell: sh
        run: npm list
      - name: Run tests
        shell: sh
        run: node --test bindings/node/*_test.js
