name: Publish packages

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build_node:
    name: Build NodeJS binaries on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          #node-version: ${{inputs.node-version}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
